apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zgxvsqvfx-dotnet-basic
  janus-idp.io/tekton: zgxvsqvfx-dotnet-basic
  backstage.io/kubernetes-id: zgxvsqvfx-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zgxvsqvfx-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
